#pragma once

#include <iterator>

// This value is automatically generated by the build tool during pre-build event
// If not generated yet, use a default value for compilation
#ifndef EL_GIT_TAG_INFO
#define EL_GIT_TAG_INFO "0.0.0.0-dev"
#endif

// Helper function to check if a character is a digit
constexpr bool el_isdigit(char c);

// Template function to validate git tag format (xx.xx.xx.xx)
// Returns 0 if valid, -1 if invalid
// Format requirements:
// - Must have exactly 3 dots
// - Numbers before the first 3 dots must be digits only
// - Can have additional characters after the third dot
template <typename Iterator>
constexpr int el_git_tag_valid_check(Iterator it);

// Template instantiation for common string types
extern template int el_git_tag_valid_check<const char*>(const char* it);


